#!/usr/bin/env bash

curl https://bootstrap.pypa.io/pip/2.7/get-pip.py -o get-pip.py
python get-pip.py
PATH="~/Library/Python/2.7/bin:$PATH"

pip install -U pip
pip install -r requirements.txt

ROOT=$(git rev-parse --show-toplevel)
cd "$ROOT/ansible"
ansible-playbook -l localhost -c local test.yml -v
